### ISSUE TITLE
Proposed event 17 May - 6 Jun (dates inclusive)

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/SoA#13]
Please come up with problems in conducting the event in this period or thumbsup if you're ok with this date range.

**Comment by anchal7299** [comment]
The end date should be 7 June.

**Comment by theSage21** [comment]
My mistake. thanks for catching that :D

**Comment by theSage21** [comment]
@Shivank98 @Pratul1997 @anchal7299 @avni-srivastava @ayushisaxena22050 can we go ahead with this date setup?

Please mention any problems we might have over here.

**Comment by ayushisaxena22050** [comment]
Yes.. I think we can go ahead with this date.

**Comment by shvamabps** [comment]
Yes we can go ahead with date

**Comment by Shivank98** [comment]
Yeah looks good.

**Comment by theSage21** [comment]
Looking at how we won't have a lot of time for publicity I think we should start on 17 May and finish on 7 June both dates included.

**Comment by Shivank98** [comment]
should we close it now?

**Comment by theSage21** [comment]
Yeah. We'll reopen once we have a separate plan for the project.
