### ISSUE TITLE
Track content design

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/SoA#15]
Track content needs to be designed for the event. At the very least the following tracks need to be done. Please feel free to add your own ideas to this issue and update the task list.

- [x] Python track #21 
- [ ] DSA track
- [ ] college courses currently being taught. does it overlap with SoA?
    - [ ] distributed computing ? RAFT?

**Comment by theSage21** [comment]
@Avni_Srivastava @anchal7299 can we get at least one track done by next Saturday?

**Comment by avni-srivastava** [comment]
Will try @theSage21

**Comment by anchal7299** [comment]
Yes I will do

**Comment by smitjethwa** [comment]
data science for beginners

**Comment by theSage21** [comment]
> data science for beginners

There's been a lot of demand for that lately. We'll add that once the Python and DSA tracks are done.

**Comment by theSage21** [comment]
We'll manage individual tracks separately.
